#!/bin/bash

# Before you install:
#   sudo loginctl enable-linger <your-username>

# FIXME: working directory should be autogenerated

mkdir -p ~/.config/systemd/user/

if [ ! -f "${HOME}/routeros-bot.service" ]; then
  # copy config example to "${HOME}/routeros-bot.service"
fi

cat > ~/.config/systemd/user/routeros-bot.service <<EOF
[Unit]
Description=RouterOS bot for Telegram
After=network.target

[Service]
WorkingDirectory=%h/routeros-bot
ExecStart=/usr/bin/python3 -m app --config %h/routeros-bot.conf

[Install]
WantedBy=default.target
EOF

systemctl --user enable routeros-bot.service
systemctl --user start routeros-bot.service
